# Generated by Django 3.2.4 on 2022-08-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('company', '0002_alter_phone_assigned_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze', models.IntegerField(default=500)),
                ('silver', models.IntegerField(default=750)),
                ('gold', models.IntegerField(default=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_plan', models.CharField(blank=True, choices=[('GLOBALNET BRONZE', 'Globalnet Bronze'), ('GLOBALNET SILVER', 'Globalnet Silver'), ('GLOBALNET GOLD', 'Globalnet Gold')], max_length=64, null=True)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('possible_end_date', models.DateTimeField(blank=True, null=True)),
                ('charge_per_month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_money', to='subscriptions.subscriptionplan')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_company', to='company.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_customer', to='customer.customer')),
            ],
        ),
    ]
