# Generated by Django 3.2.4 on 2022-08-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscribers_charge_per_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='bronze',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='silver',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
