# Generated by Django 3.2.4 on 2022-08-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('assigned_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_customer', to='customer.customer')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_company', to='company.company')),
            ],
        ),
    ]
